import type { Problem } from '../types';

// Mock data for system design problems
// TODO: Replace with API calls when backend is ready
export const mockProblems: Problem[] = [
    {
        id: '1',
        title: 'Instagram System Design',
        description: 'Design a photo-sharing social media platform like Instagram',
        difficulty: 'Medium',
        requirements: [
            'User profiles',
            'Photo uploads',
            'High availability',
            '1M DAU',
        ],
        estimatedTime: '45-60 mins',
        category: 'Social Media',
        functionalRequirements: [],
        nonFunctionalRequirements: [],
        isPro: false,
    },
    {
        id: '2',
        title: 'URL Shortener',
        description: 'Design a URL shortening service like bit.ly',
        difficulty: 'Easy',
        requirements: [
            'Shorten URLs',
            'Redirect to original',
            'Analytics tracking',
            'High throughput',
        ],
        estimatedTime: '30-45 mins',
        category: 'Core Services',
        functionalRequirements: [],
        nonFunctionalRequirements: [],
        isPro: false,
    },
    {
        id: '3',
        title: 'Netflix Video Streaming',
        description: 'Design a video streaming platform like Netflix',
        difficulty: 'Hard',
        requirements: [
            'Video encoding',
            'CDN distribution',
            'Adaptive bitrate',
            '100M users',
        ],
        estimatedTime: '60-90 mins',
        category: 'Streaming',
        functionalRequirements: [],
        nonFunctionalRequirements: [],
        isPro: true,
    },
    {
        id: '4',
        title: 'Uber Ride Sharing',
        description: 'Design a real-time ride-sharing system',
        difficulty: 'Hard',
        requirements: [
            'Real-time matching',
            'Location tracking',
            'Pricing algorithm',
            'High consistency',
        ],
        estimatedTime: '60-90 mins',
        category: 'Real-time Systems',
        functionalRequirements: [],
        nonFunctionalRequirements: [],
        isPro: true,
    },
    {
        id: '5',
        title: 'Twitter Timeline',
        description: 'Design the timeline feed for a social media platform',
        difficulty: 'Medium',
        requirements: [
            'Real-time updates',
            'Follower model',
            'High read/write ratio',
            '500M users',
        ],
        estimatedTime: '45-60 mins',
        category: 'Social Media',
        functionalRequirements: [],
        nonFunctionalRequirements: [],
        isPro: false,
    },
];
